# ClientHello/ServerHello, HMAC verification

import os
from config import PROTOCOL_VERSION, NONCE_SIZE, SESSION_ID_SIZE, HMAC_SIZE
from security.crypto import compute_hmac, verify_hmac


class HandshakeError(Exception):
    pass


def build_client_hello(psk: bytes) -> tuple[bytes, bytes]:
    """
    Build a ClientHello payload.

    Args:
        psk: The pre-shared key

    Returns:
        (payload, client_nonce)
        - payload: The bytes to send as the ClientHello message
        - client_nonce: The random nonce generated for this handshake
    """
    client_nonce = os.urandom(NONCE_SIZE)
    mac = compute_hmac(psk, client_nonce + PROTOCOL_VERSION)
    payload = client_nonce + PROTOCOL_VERSION + mac
    return payload, client_nonce


def parse_client_hello(psk: bytes, payload: bytes) -> bytes:
    """
    Parse a ClientHello payload and verify its HMAC.

    Args:
        psk: The pre-shared key
        payload: The bytes received as the ClientHello message

    Returns:
        client_nonce if valid

    Raises:
        HandshakeError if the payload is malformed or HMAC verification fails
    """
    expected_len = NONCE_SIZE + len(PROTOCOL_VERSION) + HMAC_SIZE
    if len(payload) != expected_len:
        raise HandshakeError(
            f"Invalid ClientHello length: expected {expected_len}, got {len(payload)}."
        )

    client_nonce = payload[:NONCE_SIZE]
    protocol = payload[NONCE_SIZE : NONCE_SIZE + len(PROTOCOL_VERSION)]
    mac = payload[-HMAC_SIZE:]

    if protocol != PROTOCOL_VERSION:
        raise HandshakeError("Unsupported protocol version.")

    data_to_mac = client_nonce + protocol
    if not verify_hmac(psk, data_to_mac, mac):
        raise HandshakeError("ClientHello HMAC verification failed.")

    return client_nonce


def build_server_hello(psk: bytes, client_nonce: bytes) -> tuple[bytes, bytes, bytes]:
    """
    Build a ServerHello payload.

    Args:
        psk: The pre-shared key
        client_nonce: The nonce received from the client

    Returns:
        (payload, server_nonce, session_id)
        - payload: The bytes to send as the ServerHello message
        - server_nonce: The random nonce generated for this handshake
        - session_id: The random session ID for this connection
    """
    server_nonce = os.urandom(NONCE_SIZE)
    session_id = os.urandom(SESSION_ID_SIZE)
    data_to_mac = client_nonce + server_nonce + session_id
    mac = compute_hmac(psk, data_to_mac)
    payload = server_nonce + session_id + mac
    return payload, server_nonce, session_id


def parse_server_hello(psk: bytes, client_nonce: bytes, payload: bytes) -> tuple[bytes, bytes]:
    """
    Parse a ServerHello payload and verify its HMAC against the expected client_nonce.

    Args:
        psk: The pre-shared key
        client_nonce: The nonce that was sent in the ClientHello
        payload: The bytes received as the ServerHello message

    Returns:
        (server_nonce, session_id) if valid
        - server_nonce: The nonce generated by the server
        - session_id: The session ID for this connection

    Raises:
        HandshakeError if the payload is malformed or HMAC verification fails
    """
    expected_len = NONCE_SIZE + SESSION_ID_SIZE + HMAC_SIZE
    if len(payload) != expected_len:
        raise HandshakeError(
            f"Invalid ServerHello length: expected {expected_len}, got {len(payload)}."
        )

    server_nonce = payload[:NONCE_SIZE]
    session_id = payload[NONCE_SIZE : NONCE_SIZE + SESSION_ID_SIZE]
    mac = payload[-HMAC_SIZE:]

    data_to_mac = client_nonce + server_nonce + session_id
    if not verify_hmac(psk, data_to_mac, mac):
        raise HandshakeError("ServerHello HMAC verification failed.")

    return server_nonce, session_id
